package com.example

class App {
    static void main(String[] args) {
        def p = new GSortedProperties()
        p.put("apple", "one")
        p.put("beta", "two")
        p.put("coffee", "three")
        def f = new File("example.properties")
        println "> cat ${f.name}"
        f.withOutputStream { stream -> p.store(stream, "Generated by the App.") }
        f.eachLine {
            println it
        }
    }
}

class GSortedProperties extends Properties {
    @Override
    Enumeration<Object> keys() {
        def keys = Collections.list(super.keys())
        keys.sort { a, b -> (a.toString() <=> b.toString()) }
        return Collections.enumeration(keys)
    }
}